### DIMENSIONES, TENSORES Y RESHAPE

<div>
    <p style = 'text-align:center;'>
        <img src="imgs/dimensions.png" width="700px">
    </p>
</div>

In [1]:
#Importamos las librerías a emplear
import numpy as np

#### ESCALARES

In [8]:
x = np.array(42)

print("Forma:", x.shape)            #Forma
print("# de dimensiones:", x.ndim)  #Número de dimensiones

Forma: ()
# de dimensiones: 0


#### VECTORES

In [9]:
x = np.array([1, 2, 3, 4, 5, 6])

print("Forma:", x.shape)            #Forma (6 posiciones)
print("# de dimensiones:", x.ndim)  #Número de dimensiones

Forma: (6,)
# de dimensiones: 1


#### MATRICES

In [13]:
x = np.array([[1, 2, 3, 4, 5, 6],
            [11, 12, 13, 14, 15, 16]])

print("Forma:", x.shape)            #Forma
print("# de dimensiones:", x.ndim)  #Número de dimensiones

Forma: (2, 6)
# de dimensiones: 2


#### TENSORES

In [16]:
x = np.array([
    [[1, 2, 3, 4, 5, 6], [11, 12, 13, 14, 15, 16]],
    [[21, 22, 23, 24, 25, 26], [31, 32, 33, 34, 35, 36]]
])

print("Forma:", x.shape)            #Forma
print("# de dimensiones:", x.ndim)  #Número de dimensiones

Forma: (2, 2, 6)
# de dimensiones: 3


In [23]:
x = np.array([
    [[1, 2, 3, 4, 5, 6], [7, 8, 9, 10, 11, 12]],
    [[21, 22, 23, 24, 25, 26], [27, 28, 29, 30, 31, 32]],
    [[41, 42, 43, 44, 45, 46], [47, 48, 49, 50, 51, 52]]
])

print("Forma:", x.shape)            #Forma: 3matrices de 2x6
print("# de dimensiones:", x.ndim)  #Número de dimensiones

Forma: (3, 2, 6)
# de dimensiones: 3


#### RESHAPE

In [26]:
#Creamos una matriz
x = np.array([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7]
        ])

#Tenemos de una matriz de:
x.shape #Forma

(4, 2)

In [28]:
#Cambiamos la forma de nuestra matriz
x.reshape(8, 1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7]])

In [31]:
#Cambiamos la forma de nuestra matriz
x.reshape(2, 4)

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [36]:
#Transpuesta
np.transpose(x)

array([[0, 2, 4, 6],
       [1, 3, 5, 7]])

In [37]:
#Transpuesta
x.T

array([[0, 2, 4, 6],
       [1, 3, 5, 7]])